//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imslip_v1p0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}comment" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}referential"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}temporal"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}privacy"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}ext_contentype" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "comment",
    "referentialsAndTemporalsAndPrivacies",
    "extContentype"
})
@XmlRootElement(name = "contentype")
public class Contentype {

    protected Comment comment;
    @XmlElements({
        @XmlElement(name = "referential", type = Referential.class),
        @XmlElement(name = "temporal", type = Temporal.class),
        @XmlElement(name = "privacy", type = Privacy.class)
    })
    protected List<Object> referentialsAndTemporalsAndPrivacies;
    @XmlElement(name = "ext_contentype")
    protected Object extContentype;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the referentialsAndTemporalsAndPrivacies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referentialsAndTemporalsAndPrivacies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferentialsAndTemporalsAndPrivacies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Referential }
     * {@link Temporal }
     * {@link Privacy }
     * 
     * 
     */
    public List<Object> getReferentialsAndTemporalsAndPrivacies() {
        if (referentialsAndTemporalsAndPrivacies == null) {
            referentialsAndTemporalsAndPrivacies = new ArrayList<Object>();
        }
        return this.referentialsAndTemporalsAndPrivacies;
    }

    /**
     * Gets the value of the extContentype property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getExtContentype() {
        return extContentype;
    }

    /**
     * Sets the value of the extContentype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setExtContentype(Object value) {
        this.extContentype = value;
    }

}
