//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imslip_v1p0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}sourcedid"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}text"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourcedidsAndTexts"
})
@XmlRootElement(name = "learningactivityref")
public class Learningactivityref {

    @XmlElements({
        @XmlElement(name = "sourcedid", type = Sourcedid.class),
        @XmlElement(name = "text", type = Text.class)
    })
    protected List<Object> sourcedidsAndTexts;

    /**
     * Gets the value of the sourcedidsAndTexts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourcedidsAndTexts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourcedidsAndTexts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sourcedid }
     * {@link Text }
     * 
     * 
     */
    public List<Object> getSourcedidsAndTexts() {
        if (sourcedidsAndTexts == null) {
            sourcedidsAndTexts = new ArrayList<Object>();
        }
        return this.sourcedidsAndTexts;
    }

}
