//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imslip_v1p0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}comment" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}contentype" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}identification"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}goal"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}qcl"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}activity"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}competency"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}transcript"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}accessibility"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}interest"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}affiliation"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}securitykey"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}relationship"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}ext_learnerinfo"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imslip_v1p0}lang.attr"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "comment",
    "contentype",
    "identificationsAndGoalsAndQcls"
})
@XmlRootElement(name = "learnerinformation")
public class Learnerinformation {

    protected Comment comment;
    protected Contentype contentype;
    @XmlElements({
        @XmlElement(name = "identification", type = Identification.class),
        @XmlElement(name = "goal", type = Goal.class),
        @XmlElement(name = "qcl", type = Qcl.class),
        @XmlElement(name = "activity", type = Activity.class),
        @XmlElement(name = "competency", type = Competency.class),
        @XmlElement(name = "transcript", type = Transcript.class),
        @XmlElement(name = "accessibility", type = Accessibility.class),
        @XmlElement(name = "interest", type = Interest.class),
        @XmlElement(name = "affiliation", type = Affiliation.class),
        @XmlElement(name = "securitykey", type = Securitykey.class),
        @XmlElement(name = "relationship", type = Relationship.class),
        @XmlElement(name = "ext_learnerinfo")
    })
    protected List<Object> identificationsAndGoalsAndQcls;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the contentype property.
     * 
     * @return
     *     possible object is
     *     {@link Contentype }
     *     
     */
    public Contentype getContentype() {
        return contentype;
    }

    /**
     * Sets the value of the contentype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contentype }
     *     
     */
    public void setContentype(Contentype value) {
        this.contentype = value;
    }

    /**
     * Gets the value of the identificationsAndGoalsAndQcls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificationsAndGoalsAndQcls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificationsAndGoalsAndQcls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Identification }
     * {@link Goal }
     * {@link Qcl }
     * {@link Activity }
     * {@link Competency }
     * {@link Transcript }
     * {@link Accessibility }
     * {@link Interest }
     * {@link Affiliation }
     * {@link Securitykey }
     * {@link Relationship }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getIdentificationsAndGoalsAndQcls() {
        if (identificationsAndGoalsAndQcls == null) {
            identificationsAndGoalsAndQcls = new ArrayList<Object>();
        }
        return this.identificationsAndGoalsAndQcls;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        if (lang == null) {
            return "en";
        } else {
            return lang;
        }
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
