//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imslip_v1p0;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.imsglobal.xsd.imslip_v1p0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Source_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "source");
    private final static QName _Id_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "id");
    private final static QName _Indexid_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "indexid");
    private final static QName _Fielddata_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "fielddata");
    private final static QName _Datetime_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "datetime");
    private final static QName _ExtDate_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_date");
    private final static QName _ExtContentype_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_contentype");
    private final static QName _Web_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "web");
    private final static QName _Email_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "email");
    private final static QName _Countrycode_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "countrycode");
    private final static QName _Areacode_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "areacode");
    private final static QName _Indnumber_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "indnumber");
    private final static QName _Extnumber_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "extnumber");
    private final static QName _Uid_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "uid");
    private final static QName _Agentid_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "agentid");
    private final static QName _ExtIdentification_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_identification");
    private final static QName _Registrationno_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "registrationno");
    private final static QName _ExtGoal_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_goal");
    private final static QName _ExtQcl_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_qcl");
    private final static QName _ExtDefinition_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_definition");
    private final static QName _ExtTestimonial_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_testimonial");
    private final static QName _Evaluationid_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "evaluationid");
    private final static QName _Contentref_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "contentref");
    private final static QName _ExtObjectives_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_objectives");
    private final static QName _Noofattempts_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "noofattempts");
    private final static QName _ExtEvaluation_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_evaluation");
    private final static QName _ExtActivity_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_activity");
    private final static QName _ExtExrefrecord_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_exrefrecord");
    private final static QName _ExtCompetency_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_competency");
    private final static QName _ExtTranscript_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_transcript");
    private final static QName _ExtLanguage_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_language");
    private final static QName _ExtEligibility_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_eligibility");
    private final static QName _ExtPreference_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_preference");
    private final static QName _ExtDisability_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_disability");
    private final static QName _ExtAccessibility_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_accessibility");
    private final static QName _ExtInterest_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_interest");
    private final static QName _Affiliationid_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "affiliationid");
    private final static QName _ExtRole_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_role");
    private final static QName _ExtAffiliation_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_affiliation");
    private final static QName _ExtSecuritykey_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_securitykey");
    private final static QName _ExtRelationship_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_relationship");
    private final static QName _ExtLearnerinfo_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_learnerinfo");
    private final static QName _Lat_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "lat");
    private final static QName _Lon_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "lon");
    private final static QName _ExtProduct_QNAME = new QName("http://www.imsglobal.org/xsd/imslip_v1p0", "ext_product");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.imsglobal.xsd.imslip_v1p0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Identification }
     * 
     */
    public Identification createIdentification() {
        return new Identification();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link Contentype }
     * 
     */
    public Contentype createContentype() {
        return new Contentype();
    }

    /**
     * Create an instance of {@link Referential }
     * 
     */
    public Referential createReferential() {
        return new Referential();
    }

    /**
     * Create an instance of {@link Sourcedid }
     * 
     */
    public Sourcedid createSourcedid() {
        return new Sourcedid();
    }

    /**
     * Create an instance of {@link Temporal }
     * 
     */
    public Temporal createTemporal() {
        return new Temporal();
    }

    /**
     * Create an instance of {@link Typename }
     * 
     */
    public Typename createTypename() {
        return new Typename();
    }

    /**
     * Create an instance of {@link Tysource }
     * 
     */
    public Tysource createTysource() {
        return new Tysource();
    }

    /**
     * Create an instance of {@link Tyvalue }
     * 
     */
    public Tyvalue createTyvalue() {
        return new Tyvalue();
    }

    /**
     * Create an instance of {@link Temporalfield }
     * 
     */
    public Temporalfield createTemporalfield() {
        return new Temporalfield();
    }

    /**
     * Create an instance of {@link Fieldlabel }
     * 
     */
    public Fieldlabel createFieldlabel() {
        return new Fieldlabel();
    }

    /**
     * Create an instance of {@link Privacy }
     * 
     */
    public Privacy createPrivacy() {
        return new Privacy();
    }

    /**
     * Create an instance of {@link Privacyfield }
     * 
     */
    public Privacyfield createPrivacyfield() {
        return new Privacyfield();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Short }
     * 
     */
    public Short createShort() {
        return new Short();
    }

    /**
     * Create an instance of {@link Long }
     * 
     */
    public Long createLong() {
        return new Long();
    }

    /**
     * Create an instance of {@link Full }
     * 
     */
    public Full createFull() {
        return new Full();
    }

    /**
     * Create an instance of {@link Media }
     * 
     */
    public Media createMedia() {
        return new Media();
    }

    /**
     * Create an instance of {@link Formname }
     * 
     */
    public Formname createFormname() {
        return new Formname();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Partname }
     * 
     */
    public Partname createPartname() {
        return new Partname();
    }

    /**
     * Create an instance of {@link AqurateAddress }
     * 
     */
    public AqurateAddress createAqurateAddress() {
        return new AqurateAddress();
    }

    /**
     * Create an instance of {@link Contactinfo }
     * 
     */
    public Contactinfo createContactinfo() {
        return new Contactinfo();
    }

    /**
     * Create an instance of {@link Pager }
     * 
     */
    public Pager createPager() {
        return new Pager();
    }

    /**
     * Create an instance of {@link Mobile }
     * 
     */
    public Mobile createMobile() {
        return new Mobile();
    }

    /**
     * Create an instance of {@link Facsimile }
     * 
     */
    public Facsimile createFacsimile() {
        return new Facsimile();
    }

    /**
     * Create an instance of {@link Telephone }
     * 
     */
    public Telephone createTelephone() {
        return new Telephone();
    }

    /**
     * Create an instance of {@link Demographics }
     * 
     */
    public Demographics createDemographics() {
        return new Demographics();
    }

    /**
     * Create an instance of {@link Representation }
     * 
     */
    public Representation createRepresentation() {
        return new Representation();
    }

    /**
     * Create an instance of {@link Gender }
     * 
     */
    public Gender createGender() {
        return new Gender();
    }

    /**
     * Create an instance of {@link Placeofbirth }
     * 
     */
    public Placeofbirth createPlaceofbirth() {
        return new Placeofbirth();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Agentdomain }
     * 
     */
    public Agentdomain createAgentdomain() {
        return new Agentdomain();
    }

    /**
     * Create an instance of {@link Priority }
     * 
     */
    public Priority createPriority() {
        return new Priority();
    }

    /**
     * Create an instance of {@link Proficiency }
     * 
     */
    public Proficiency createProficiency() {
        return new Proficiency();
    }

    /**
     * Create an instance of {@link Pobox }
     * 
     */
    public Pobox createPobox() {
        return new Pobox();
    }

    /**
     * Create an instance of {@link Locality }
     * 
     */
    public Locality createLocality() {
        return new Locality();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Statepr }
     * 
     */
    public Statepr createStatepr() {
        return new Statepr();
    }

    /**
     * Create an instance of {@link Region }
     * 
     */
    public Region createRegion() {
        return new Region();
    }

    /**
     * Create an instance of {@link Postcode }
     * 
     */
    public Postcode createPostcode() {
        return new Postcode();
    }

    /**
     * Create an instance of {@link Timezone }
     * 
     */
    public Timezone createTimezone() {
        return new Timezone();
    }

    /**
     * Create an instance of {@link Nonfieldedstreetaddress }
     * 
     */
    public Nonfieldedstreetaddress createNonfieldedstreetaddress() {
        return new Nonfieldedstreetaddress();
    }

    /**
     * Create an instance of {@link Complex }
     * 
     */
    public Complex createComplex() {
        return new Complex();
    }

    /**
     * Create an instance of {@link Streetnumber }
     * 
     */
    public Streetnumber createStreetnumber() {
        return new Streetnumber();
    }

    /**
     * Create an instance of {@link Streetprefix }
     * 
     */
    public Streetprefix createStreetprefix() {
        return new Streetprefix();
    }

    /**
     * Create an instance of {@link Streetname }
     * 
     */
    public Streetname createStreetname() {
        return new Streetname();
    }

    /**
     * Create an instance of {@link Streetype }
     * 
     */
    public Streetype createStreetype() {
        return new Streetype();
    }

    /**
     * Create an instance of {@link Streetsuffix }
     * 
     */
    public Streetsuffix createStreetsuffix() {
        return new Streetsuffix();
    }

    /**
     * Create an instance of {@link Apttype }
     * 
     */
    public Apttype createApttype() {
        return new Apttype();
    }

    /**
     * Create an instance of {@link Aptnumprefix }
     * 
     */
    public Aptnumprefix createAptnumprefix() {
        return new Aptnumprefix();
    }

    /**
     * Create an instance of {@link Aptnumber }
     * 
     */
    public Aptnumber createAptnumber() {
        return new Aptnumber();
    }

    /**
     * Create an instance of {@link Aptnumsuffix }
     * 
     */
    public Aptnumsuffix createAptnumsuffix() {
        return new Aptnumsuffix();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Prefcode }
     * 
     */
    public Prefcode createPrefcode() {
        return new Prefcode();
    }

    /**
     * Create an instance of {@link Learnerinformation }
     * 
     */
    public Learnerinformation createLearnerinformation() {
        return new Learnerinformation();
    }

    /**
     * Create an instance of {@link Goal }
     * 
     */
    public Goal createGoal() {
        return new Goal();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Qcl }
     * 
     */
    public Qcl createQcl() {
        return new Qcl();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link Level }
     * 
     */
    public Level createLevel() {
        return new Level();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link Units }
     * 
     */
    public Units createUnits() {
        return new Units();
    }

    /**
     * Create an instance of {@link Unitsfield }
     * 
     */
    public Unitsfield createUnitsfield() {
        return new Unitsfield();
    }

    /**
     * Create an instance of {@link Learningactivityref }
     * 
     */
    public Learningactivityref createLearningactivityref() {
        return new Learningactivityref();
    }

    /**
     * Create an instance of {@link Definition }
     * 
     */
    public Definition createDefinition() {
        return new Definition();
    }

    /**
     * Create an instance of {@link Definitionfield }
     * 
     */
    public Definitionfield createDefinitionfield() {
        return new Definitionfield();
    }

    /**
     * Create an instance of {@link AqurateProduct }
     * 
     */
    public AqurateProduct createAqurateProduct() {
        return new AqurateProduct();
    }

    /**
     * Create an instance of {@link Testimonial }
     * 
     */
    public Testimonial createTestimonial() {
        return new Testimonial();
    }

    /**
     * Create an instance of {@link Evaluation }
     * 
     */
    public Evaluation createEvaluation() {
        return new Evaluation();
    }

    /**
     * Create an instance of {@link Evalmetadata }
     * 
     */
    public Evalmetadata createEvalmetadata() {
        return new Evalmetadata();
    }

    /**
     * Create an instance of {@link Evalmetadatafield }
     * 
     */
    public Evalmetadatafield createEvalmetadatafield() {
        return new Evalmetadatafield();
    }

    /**
     * Create an instance of {@link Objectives }
     * 
     */
    public Objectives createObjectives() {
        return new Objectives();
    }

    /**
     * Create an instance of {@link Duration }
     * 
     */
    public Duration createDuration() {
        return new Duration();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Interpretscore }
     * 
     */
    public Interpretscore createInterpretscore() {
        return new Interpretscore();
    }

    /**
     * Create an instance of {@link Score }
     * 
     */
    public Score createScore() {
        return new Score();
    }

    /**
     * Create an instance of {@link Competency }
     * 
     */
    public Competency createCompetency() {
        return new Competency();
    }

    /**
     * Create an instance of {@link Exrefrecord }
     * 
     */
    public Exrefrecord createExrefrecord() {
        return new Exrefrecord();
    }

    /**
     * Create an instance of {@link Recformat }
     * 
     */
    public Recformat createRecformat() {
        return new Recformat();
    }

    /**
     * Create an instance of {@link Recdata }
     * 
     */
    public Recdata createRecdata() {
        return new Recdata();
    }

    /**
     * Create an instance of {@link Transcript }
     * 
     */
    public Transcript createTranscript() {
        return new Transcript();
    }

    /**
     * Create an instance of {@link Accessibility }
     * 
     */
    public Accessibility createAccessibility() {
        return new Accessibility();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link Eligibility }
     * 
     */
    public Eligibility createEligibility() {
        return new Eligibility();
    }

    /**
     * Create an instance of {@link Preference }
     * 
     */
    public Preference createPreference() {
        return new Preference();
    }

    /**
     * Create an instance of {@link Disability }
     * 
     */
    public Disability createDisability() {
        return new Disability();
    }

    /**
     * Create an instance of {@link Interest }
     * 
     */
    public Interest createInterest() {
        return new Interest();
    }

    /**
     * Create an instance of {@link Affiliation }
     * 
     */
    public Affiliation createAffiliation() {
        return new Affiliation();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Securitykey }
     * 
     */
    public Securitykey createSecuritykey() {
        return new Securitykey();
    }

    /**
     * Create an instance of {@link Keyfields }
     * 
     */
    public Keyfields createKeyfields() {
        return new Keyfields();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link Tuple }
     * 
     */
    public Tuple createTuple() {
        return new Tuple();
    }

    /**
     * Create an instance of {@link Tuplesource }
     * 
     */
    public Tuplesource createTuplesource() {
        return new Tuplesource();
    }

    /**
     * Create an instance of {@link Tuplerelation }
     * 
     */
    public Tuplerelation createTuplerelation() {
        return new Tuplerelation();
    }

    /**
     * Create an instance of {@link Tupledest }
     * 
     */
    public Tupledest createTupledest() {
        return new Tupledest();
    }

    /**
     * Create an instance of {@link Street }
     * 
     */
    public Street createStreet() {
        return new Street();
    }

    /**
     * Create an instance of {@link Geo }
     * 
     */
    public Geo createGeo() {
        return new Geo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "source")
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "indexid")
    public JAXBElement<String> createIndexid(String value) {
        return new JAXBElement<String>(_Indexid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "fielddata")
    public JAXBElement<String> createFielddata(String value) {
        return new JAXBElement<String>(_Fielddata_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "datetime")
    public JAXBElement<XMLGregorianCalendar> createDatetime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Datetime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_date")
    public JAXBElement<Object> createExtDate(Object value) {
        return new JAXBElement<Object>(_ExtDate_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_contentype")
    public JAXBElement<Object> createExtContentype(Object value) {
        return new JAXBElement<Object>(_ExtContentype_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "web")
    public JAXBElement<String> createWeb(String value) {
        return new JAXBElement<String>(_Web_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "countrycode")
    public JAXBElement<String> createCountrycode(String value) {
        return new JAXBElement<String>(_Countrycode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "areacode")
    public JAXBElement<String> createAreacode(String value) {
        return new JAXBElement<String>(_Areacode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "indnumber")
    public JAXBElement<String> createIndnumber(String value) {
        return new JAXBElement<String>(_Indnumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "extnumber")
    public JAXBElement<String> createExtnumber(String value) {
        return new JAXBElement<String>(_Extnumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "uid")
    public JAXBElement<String> createUid(String value) {
        return new JAXBElement<String>(_Uid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "agentid")
    public JAXBElement<String> createAgentid(String value) {
        return new JAXBElement<String>(_Agentid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_identification")
    public JAXBElement<Object> createExtIdentification(Object value) {
        return new JAXBElement<Object>(_ExtIdentification_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "registrationno")
    public JAXBElement<String> createRegistrationno(String value) {
        return new JAXBElement<String>(_Registrationno_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_goal")
    public JAXBElement<Object> createExtGoal(Object value) {
        return new JAXBElement<Object>(_ExtGoal_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_qcl")
    public JAXBElement<Object> createExtQcl(Object value) {
        return new JAXBElement<Object>(_ExtQcl_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_definition")
    public JAXBElement<Object> createExtDefinition(Object value) {
        return new JAXBElement<Object>(_ExtDefinition_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_testimonial")
    public JAXBElement<Object> createExtTestimonial(Object value) {
        return new JAXBElement<Object>(_ExtTestimonial_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "evaluationid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    public JAXBElement<String> createEvaluationid(String value) {
        return new JAXBElement<String>(_Evaluationid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "contentref")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    public JAXBElement<String> createContentref(String value) {
        return new JAXBElement<String>(_Contentref_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_objectives")
    public JAXBElement<Object> createExtObjectives(Object value) {
        return new JAXBElement<Object>(_ExtObjectives_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "noofattempts")
    public JAXBElement<BigInteger> createNoofattempts(BigInteger value) {
        return new JAXBElement<BigInteger>(_Noofattempts_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_evaluation")
    public JAXBElement<Object> createExtEvaluation(Object value) {
        return new JAXBElement<Object>(_ExtEvaluation_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_activity")
    public JAXBElement<Object> createExtActivity(Object value) {
        return new JAXBElement<Object>(_ExtActivity_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_exrefrecord")
    public JAXBElement<Object> createExtExrefrecord(Object value) {
        return new JAXBElement<Object>(_ExtExrefrecord_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_competency")
    public JAXBElement<Object> createExtCompetency(Object value) {
        return new JAXBElement<Object>(_ExtCompetency_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_transcript")
    public JAXBElement<Object> createExtTranscript(Object value) {
        return new JAXBElement<Object>(_ExtTranscript_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_language")
    public JAXBElement<Object> createExtLanguage(Object value) {
        return new JAXBElement<Object>(_ExtLanguage_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_eligibility")
    public JAXBElement<Object> createExtEligibility(Object value) {
        return new JAXBElement<Object>(_ExtEligibility_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_preference")
    public JAXBElement<Object> createExtPreference(Object value) {
        return new JAXBElement<Object>(_ExtPreference_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_disability")
    public JAXBElement<Object> createExtDisability(Object value) {
        return new JAXBElement<Object>(_ExtDisability_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_accessibility")
    public JAXBElement<Object> createExtAccessibility(Object value) {
        return new JAXBElement<Object>(_ExtAccessibility_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_interest")
    public JAXBElement<Object> createExtInterest(Object value) {
        return new JAXBElement<Object>(_ExtInterest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "affiliationid")
    public JAXBElement<String> createAffiliationid(String value) {
        return new JAXBElement<String>(_Affiliationid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_role")
    public JAXBElement<Object> createExtRole(Object value) {
        return new JAXBElement<Object>(_ExtRole_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_affiliation")
    public JAXBElement<Object> createExtAffiliation(Object value) {
        return new JAXBElement<Object>(_ExtAffiliation_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_securitykey")
    public JAXBElement<Object> createExtSecuritykey(Object value) {
        return new JAXBElement<Object>(_ExtSecuritykey_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_relationship")
    public JAXBElement<Object> createExtRelationship(Object value) {
        return new JAXBElement<Object>(_ExtRelationship_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_learnerinfo")
    public JAXBElement<Object> createExtLearnerinfo(Object value) {
        return new JAXBElement<Object>(_ExtLearnerinfo_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "lat")
    public JAXBElement<String> createLat(String value) {
        return new JAXBElement<String>(_Lat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "lon")
    public JAXBElement<String> createLon(String value) {
        return new JAXBElement<String>(_Lon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", name = "ext_product")
    public JAXBElement<Object> createExtProduct(Object value) {
        return new JAXBElement<Object>(_ExtProduct_QNAME, Object.class, null, value);
    }

}
