//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imslip_v1p0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}comment" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}media"/&gt;
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}contentref"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}ext_objectives" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="view" default="All"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="All"/&gt;
 *             &lt;enumeration value="Administrator"/&gt;
 *             &lt;enumeration value="AdminAuthority"/&gt;
 *             &lt;enumeration value="Assessor"/&gt;
 *             &lt;enumeration value="Author"/&gt;
 *             &lt;enumeration value="Candidate"/&gt;
 *             &lt;enumeration value="InvigilatorProctor"/&gt;
 *             &lt;enumeration value="Psychometrician"/&gt;
 *             &lt;enumeration value="Scorer"/&gt;
 *             &lt;enumeration value="Tutor"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "comment",
    "mediasAndContentreves",
    "extObjectives"
})
@XmlRootElement(name = "objectives")
public class Objectives {

    protected Comment comment;
    @XmlElementRefs({
        @XmlElementRef(name = "contentref", namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "media", namespace = "http://www.imsglobal.org/xsd/imslip_v1p0", type = Media.class, required = false)
    })
    protected List<Object> mediasAndContentreves;
    @XmlElement(name = "ext_objectives")
    protected Object extObjectives;
    @XmlAttribute(name = "view")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String view;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the mediasAndContentreves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mediasAndContentreves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMediasAndContentreves().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Media }
     * 
     * 
     */
    public List<Object> getMediasAndContentreves() {
        if (mediasAndContentreves == null) {
            mediasAndContentreves = new ArrayList<Object>();
        }
        return this.mediasAndContentreves;
    }

    /**
     * Gets the value of the extObjectives property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getExtObjectives() {
        return extObjectives;
    }

    /**
     * Sets the value of the extObjectives property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setExtObjectives(Object value) {
        this.extObjectives = value;
    }

    /**
     * Gets the value of the view property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getView() {
        if (view == null) {
            return "All";
        } else {
            return view;
        }
    }

    /**
     * Sets the value of the view property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setView(String value) {
        this.view = value;
    }

}
