//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imslip_v1p0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}tuplesource"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}tuplerelation"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imslip_v1p0}tupledest" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tuplesource",
    "tuplerelation",
    "tupledests"
})
@XmlRootElement(name = "tuple")
public class Tuple {

    @XmlElement(required = true)
    protected Tuplesource tuplesource;
    @XmlElement(required = true)
    protected Tuplerelation tuplerelation;
    @XmlElement(name = "tupledest", required = true)
    protected List<Tupledest> tupledests;

    /**
     * Gets the value of the tuplesource property.
     * 
     * @return
     *     possible object is
     *     {@link Tuplesource }
     *     
     */
    public Tuplesource getTuplesource() {
        return tuplesource;
    }

    /**
     * Sets the value of the tuplesource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tuplesource }
     *     
     */
    public void setTuplesource(Tuplesource value) {
        this.tuplesource = value;
    }

    /**
     * Gets the value of the tuplerelation property.
     * 
     * @return
     *     possible object is
     *     {@link Tuplerelation }
     *     
     */
    public Tuplerelation getTuplerelation() {
        return tuplerelation;
    }

    /**
     * Sets the value of the tuplerelation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tuplerelation }
     *     
     */
    public void setTuplerelation(Tuplerelation value) {
        this.tuplerelation = value;
    }

    /**
     * Gets the value of the tupledests property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tupledests property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTupledests().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tupledest }
     * 
     * 
     */
    public List<Tupledest> getTupledests() {
        if (tupledests == null) {
            tupledests = new ArrayList<Tupledest>();
        }
        return this.tupledests;
    }

}
