//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._1998.math.mathml.Math;
import org.w3._2001.xinclude.Include;


/**
 * <p>Java class for blockquote.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="blockquote.Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}blockquote.ContentGroup"/&gt;
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}blockquote.AttrGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "blockquote.Type", propOrder = {
    "positionObjectStagesAndCustomInteractionsAndDrawingInteractions"
})
@XmlRootElement(name = "blockquote")
public class Blockquote {

    @XmlElements({
        @XmlElement(name = "positionObjectStage", type = PositionObjectStage.class),
        @XmlElement(name = "customInteraction", type = CustomInteraction.class),
        @XmlElement(name = "drawingInteraction", type = DrawingInteraction.class),
        @XmlElement(name = "gapMatchInteraction", type = GapMatchInteraction.class),
        @XmlElement(name = "matchInteraction", type = MatchInteraction.class),
        @XmlElement(name = "graphicGapMatchInteraction", type = GraphicGapMatchInteraction.class),
        @XmlElement(name = "hotspotInteraction", type = HotspotInteraction.class),
        @XmlElement(name = "graphicOrderInteraction", type = GraphicOrderInteraction.class),
        @XmlElement(name = "selectPointInteraction", type = SelectPointInteraction.class),
        @XmlElement(name = "graphicAssociateInteraction", type = GraphicAssociateInteraction.class),
        @XmlElement(name = "sliderInteraction", type = SliderInteraction.class),
        @XmlElement(name = "choiceInteraction", type = ChoiceInteraction.class),
        @XmlElement(name = "mediaInteraction", type = MediaInteraction.class),
        @XmlElement(name = "hottextInteraction", type = HottextInteraction.class),
        @XmlElement(name = "orderInteraction", type = OrderInteraction.class),
        @XmlElement(name = "extendedTextInteraction", type = ExtendedTextInteraction.class),
        @XmlElement(name = "uploadInteraction", type = UploadInteraction.class),
        @XmlElement(name = "associateInteraction", type = AssociateInteraction.class),
        @XmlElement(name = "pre", type = Pre.class),
        @XmlElement(name = "h2", type = H2 .class),
        @XmlElement(name = "h3", type = H3 .class),
        @XmlElement(name = "h1", type = H1 .class),
        @XmlElement(name = "h6", type = H6 .class),
        @XmlElement(name = "h4", type = H4 .class),
        @XmlElement(name = "h5", type = H5 .class),
        @XmlElement(name = "p", type = P.class),
        @XmlElement(name = "address", type = Address.class),
        @XmlElement(name = "dl", type = Dl.class),
        @XmlElement(name = "ol", type = Ol.class),
        @XmlElement(name = "hr", type = Hr.class),
        @XmlElement(name = "rubricBlock", type = RubricBlock.class),
        @XmlElement(name = "blockquote", type = Blockquote.class),
        @XmlElement(name = "feedbackBlock", type = FeedbackBlock.class),
        @XmlElement(name = "ul", type = Ul.class),
        @XmlElement(name = "templateBlock", type = TemplateBlock.class),
        @XmlElement(name = "table", type = Table.class),
        @XmlElement(name = "div", type = Div.class),
        @XmlElement(name = "include", namespace = "http://www.w3.org/2001/XInclude", type = Include.class),
        @XmlElement(name = "math", namespace = "http://www.w3.org/1998/Math/MathML", type = Math.class)
    })
    protected List<java.lang.Object> positionObjectStagesAndCustomInteractionsAndDrawingInteractions;
    @XmlAttribute(name = "cite")
    protected String cite;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "class")
    protected List<String> clazzs;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "label")
    protected String label;

    /**
     * Gets the value of the positionObjectStagesAndCustomInteractionsAndDrawingInteractions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the positionObjectStagesAndCustomInteractionsAndDrawingInteractions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPositionObjectStagesAndCustomInteractionsAndDrawingInteractions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PositionObjectStage }
     * {@link CustomInteraction }
     * {@link DrawingInteraction }
     * {@link GapMatchInteraction }
     * {@link MatchInteraction }
     * {@link GraphicGapMatchInteraction }
     * {@link HotspotInteraction }
     * {@link GraphicOrderInteraction }
     * {@link SelectPointInteraction }
     * {@link GraphicAssociateInteraction }
     * {@link SliderInteraction }
     * {@link ChoiceInteraction }
     * {@link MediaInteraction }
     * {@link HottextInteraction }
     * {@link OrderInteraction }
     * {@link ExtendedTextInteraction }
     * {@link UploadInteraction }
     * {@link AssociateInteraction }
     * {@link Pre }
     * {@link H2 }
     * {@link H3 }
     * {@link H1 }
     * {@link H6 }
     * {@link H4 }
     * {@link H5 }
     * {@link P }
     * {@link Address }
     * {@link Dl }
     * {@link Ol }
     * {@link Hr }
     * {@link RubricBlock }
     * {@link Blockquote }
     * {@link FeedbackBlock }
     * {@link Ul }
     * {@link TemplateBlock }
     * {@link Table }
     * {@link Div }
     * {@link Include }
     * {@link Math }
     * 
     * 
     */
    public List<java.lang.Object> getPositionObjectStagesAndCustomInteractionsAndDrawingInteractions() {
        if (positionObjectStagesAndCustomInteractionsAndDrawingInteractions == null) {
            positionObjectStagesAndCustomInteractionsAndDrawingInteractions = new ArrayList<java.lang.Object>();
        }
        return this.positionObjectStagesAndCustomInteractionsAndDrawingInteractions;
    }

    /**
     * Gets the value of the cite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCite() {
        return cite;
    }

    /**
     * Sets the value of the cite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCite(String value) {
        this.cite = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the clazzs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clazzs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClazzs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getClazzs() {
        if (clazzs == null) {
            clazzs = new ArrayList<String>();
        }
        return this.clazzs;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

}
