//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for feedbackType.Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="feedbackType.Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="adaptive"/&gt;
 *     &lt;enumeration value="nonadaptive"/&gt;
 *     &lt;enumeration value="none"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "feedbackType.Type")
@XmlEnum
public enum FeedbackTypeType {

    @XmlEnumValue("adaptive")
    ADAPTIVE("adaptive"),
    @XmlEnumValue("nonadaptive")
    NONADAPTIVE("nonadaptive"),
    @XmlEnumValue("none")
    NONE("none");
    private final String value;

    FeedbackTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FeedbackTypeType fromValue(String v) {
        for (FeedbackTypeType c: FeedbackTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
