//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for itemSessionControl.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="itemSessionControl.Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}itemSessionControl.AttrGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemSessionControl.Type")
@XmlRootElement(name = "itemSessionControl")
public class ItemSessionControl {

    @XmlAttribute(name = "maxAttempts")
    protected Integer maxAttempts;
    @XmlAttribute(name = "showFeedback")
    protected Boolean showFeedback;
    @XmlAttribute(name = "allowReview")
    protected Boolean allowReview;
    @XmlAttribute(name = "showSolution")
    protected Boolean showSolution;
    @XmlAttribute(name = "allowComment")
    protected Boolean allowComment;
    @XmlAttribute(name = "allowSkipping")
    protected Boolean allowSkipping;
    @XmlAttribute(name = "validateResponses")
    protected Boolean validateResponses;

    /**
     * Gets the value of the maxAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxAttempts() {
        return maxAttempts;
    }

    /**
     * Sets the value of the maxAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxAttempts(Integer value) {
        this.maxAttempts = value;
    }

    /**
     * Gets the value of the showFeedback property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowFeedback() {
        return showFeedback;
    }

    /**
     * Sets the value of the showFeedback property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowFeedback(Boolean value) {
        this.showFeedback = value;
    }

    /**
     * Gets the value of the allowReview property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowReview() {
        return allowReview;
    }

    /**
     * Sets the value of the allowReview property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowReview(Boolean value) {
        this.allowReview = value;
    }

    /**
     * Gets the value of the showSolution property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowSolution() {
        return showSolution;
    }

    /**
     * Sets the value of the showSolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowSolution(Boolean value) {
        this.showSolution = value;
    }

    /**
     * Gets the value of the allowComment property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowComment() {
        return allowComment;
    }

    /**
     * Sets the value of the allowComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowComment(Boolean value) {
        this.allowComment = value;
    }

    /**
     * Gets the value of the allowSkipping property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowSkipping() {
        return allowSkipping;
    }

    /**
     * Sets the value of the allowSkipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowSkipping(Boolean value) {
        this.allowSkipping = value;
    }

    /**
     * Gets the value of the validateResponses property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isValidateResponses() {
        return validateResponses;
    }

    /**
     * Sets the value of the validateResponses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValidateResponses(Boolean value) {
        this.validateResponses = value;
    }

}
