//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.imsglobal.xsd.imsqti_v2p1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Adaptive_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "adaptive");
    private final static QName _UsageDataVocabulary_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "usageDataVocabulary");
    private final static QName _Imsmd_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "imsmd");
    private final static QName _LomMetadata_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "lomMetadata");
    private final static QName _Imsqtimd_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "imsqtimd");
    private final static QName _Composite_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "composite");
    private final static QName _TimeDependent_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "timeDependent");
    private final static QName _Templates_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "templates");
    private final static QName _TextElements_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "textElements");
    private final static QName _ListElements_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "listElements");
    private final static QName _ObjectElements_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "objectElements");
    private final static QName _ObjectType_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "objectType");
    private final static QName _PresentationElements_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "presentationElements");
    private final static QName _TableElements_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "tableElements");
    private final static QName _ImageElement_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "imageElement");
    private final static QName _ImageType_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "imageType");
    private final static QName _HypertextElement_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "hypertextElement");
    private final static QName _MathElement_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "mathElement");
    private final static QName _MathVariable_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "mathVariable");
    private final static QName _FeedbackIntegrated_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "feedbackIntegrated");
    private final static QName _FeedbackModal_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "feedbackModal");
    private final static QName _Rubric_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "rubric");
    private final static QName _PrintedVariables_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "printedVariables");
    private final static QName _InteractionType_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "interactionType");
    private final static QName _ResponseRules_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "responseRules");
    private final static QName _RpTemplate_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "rpTemplate");
    private final static QName _Rounding_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "rounding");
    private final static QName _Regexp_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "regexp");
    private final static QName _FeedbackType_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "feedbackType");
    private final static QName _ItemTemplate_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "itemTemplate");
    private final static QName _SolutionAvailable_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "solutionAvailable");
    private final static QName _ToolName_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "toolName");
    private final static QName _ToolVersion_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "toolVersion");
    private final static QName _ToolVendor_QNAME = new QName("http://www.imsglobal.org/xsd/imsqti_v2p1", "toolVendor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.imsglobal.xsd.imsqti_v2p1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link A }
     * 
     */
    public A createA() {
        return new A();
    }

    /**
     * Create an instance of {@link TextEntryInteraction }
     * 
     */
    public TextEntryInteraction createTextEntryInteraction() {
        return new TextEntryInteraction();
    }

    /**
     * Create an instance of {@link InlineChoiceInteraction }
     * 
     */
    public InlineChoiceInteraction createInlineChoiceInteraction() {
        return new InlineChoiceInteraction();
    }

    /**
     * Create an instance of {@link InlineChoice }
     * 
     */
    public InlineChoice createInlineChoice() {
        return new InlineChoice();
    }

    /**
     * Create an instance of {@link PrintedVariable }
     * 
     */
    public PrintedVariable createPrintedVariable() {
        return new PrintedVariable();
    }

    /**
     * Create an instance of {@link EndAttemptInteraction }
     * 
     */
    public EndAttemptInteraction createEndAttemptInteraction() {
        return new EndAttemptInteraction();
    }

    /**
     * Create an instance of {@link Hottext }
     * 
     */
    public Hottext createHottext() {
        return new Hottext();
    }

    /**
     * Create an instance of {@link Img }
     * 
     */
    public Img createImg() {
        return new Img();
    }

    /**
     * Create an instance of {@link Br }
     * 
     */
    public Br createBr() {
        return new Br();
    }

    /**
     * Create an instance of {@link Object }
     * 
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link Pre }
     * 
     */
    public Pre createPre() {
        return new Pre();
    }

    /**
     * Create an instance of {@link Gap }
     * 
     */
    public Gap createGap() {
        return new Gap();
    }

    /**
     * Create an instance of {@link Em }
     * 
     */
    public Em createEm() {
        return new Em();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link Span }
     * 
     */
    public Span createSpan() {
        return new Span();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link Acronym }
     * 
     */
    public Acronym createAcronym() {
        return new Acronym();
    }

    /**
     * Create an instance of {@link Big }
     * 
     */
    public Big createBig() {
        return new Big();
    }

    /**
     * Create an instance of {@link Tt }
     * 
     */
    public Tt createTt() {
        return new Tt();
    }

    /**
     * Create an instance of {@link Kbd }
     * 
     */
    public Kbd createKbd() {
        return new Kbd();
    }

    /**
     * Create an instance of {@link Q }
     * 
     */
    public Q createQ() {
        return new Q();
    }

    /**
     * Create an instance of {@link I }
     * 
     */
    public I createI() {
        return new I();
    }

    /**
     * Create an instance of {@link Dfn }
     * 
     */
    public Dfn createDfn() {
        return new Dfn();
    }

    /**
     * Create an instance of {@link FeedbackInline }
     * 
     */
    public FeedbackInline createFeedbackInline() {
        return new FeedbackInline();
    }

    /**
     * Create an instance of {@link Abbr }
     * 
     */
    public Abbr createAbbr() {
        return new Abbr();
    }

    /**
     * Create an instance of {@link Strong }
     * 
     */
    public Strong createStrong() {
        return new Strong();
    }

    /**
     * Create an instance of {@link Sup }
     * 
     */
    public Sup createSup() {
        return new Sup();
    }

    /**
     * Create an instance of {@link Var }
     * 
     */
    public Var createVar() {
        return new Var();
    }

    /**
     * Create an instance of {@link Small }
     * 
     */
    public Small createSmall() {
        return new Small();
    }

    /**
     * Create an instance of {@link Samp }
     * 
     */
    public Samp createSamp() {
        return new Samp();
    }

    /**
     * Create an instance of {@link B }
     * 
     */
    public B createB() {
        return new B();
    }

    /**
     * Create an instance of {@link Cite }
     * 
     */
    public Cite createCite() {
        return new Cite();
    }

    /**
     * Create an instance of {@link TemplateInline }
     * 
     */
    public TemplateInline createTemplateInline() {
        return new TemplateInline();
    }

    /**
     * Create an instance of {@link H2 }
     * 
     */
    public H2 createH2() {
        return new H2();
    }

    /**
     * Create an instance of {@link H3 }
     * 
     */
    public H3 createH3() {
        return new H3();
    }

    /**
     * Create an instance of {@link H1 }
     * 
     */
    public H1 createH1() {
        return new H1();
    }

    /**
     * Create an instance of {@link H6 }
     * 
     */
    public H6 createH6() {
        return new H6();
    }

    /**
     * Create an instance of {@link H4 }
     * 
     */
    public H4 createH4() {
        return new H4();
    }

    /**
     * Create an instance of {@link H5 }
     * 
     */
    public H5 createH5() {
        return new H5();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Dl }
     * 
     */
    public Dl createDl() {
        return new Dl();
    }

    /**
     * Create an instance of {@link Dt }
     * 
     */
    public Dt createDt() {
        return new Dt();
    }

    /**
     * Create an instance of {@link Dd }
     * 
     */
    public Dd createDd() {
        return new Dd();
    }

    /**
     * Create an instance of {@link Ol }
     * 
     */
    public Ol createOl() {
        return new Ol();
    }

    /**
     * Create an instance of {@link Li }
     * 
     */
    public Li createLi() {
        return new Li();
    }

    /**
     * Create an instance of {@link Ul }
     * 
     */
    public Ul createUl() {
        return new Ul();
    }

    /**
     * Create an instance of {@link Hr }
     * 
     */
    public Hr createHr() {
        return new Hr();
    }

    /**
     * Create an instance of {@link RubricBlock }
     * 
     */
    public RubricBlock createRubricBlock() {
        return new RubricBlock();
    }

    /**
     * Create an instance of {@link PositionObjectStage }
     * 
     */
    public PositionObjectStage createPositionObjectStage() {
        return new PositionObjectStage();
    }

    /**
     * Create an instance of {@link PositionObjectInteraction }
     * 
     */
    public PositionObjectInteraction createPositionObjectInteraction() {
        return new PositionObjectInteraction();
    }

    /**
     * Create an instance of {@link CustomInteraction }
     * 
     */
    public CustomInteraction createCustomInteraction() {
        return new CustomInteraction();
    }

    /**
     * Create an instance of {@link DrawingInteraction }
     * 
     */
    public DrawingInteraction createDrawingInteraction() {
        return new DrawingInteraction();
    }

    /**
     * Create an instance of {@link Prompt }
     * 
     */
    public Prompt createPrompt() {
        return new Prompt();
    }

    /**
     * Create an instance of {@link GapMatchInteraction }
     * 
     */
    public GapMatchInteraction createGapMatchInteraction() {
        return new GapMatchInteraction();
    }

    /**
     * Create an instance of {@link GapText }
     * 
     */
    public GapText createGapText() {
        return new GapText();
    }

    /**
     * Create an instance of {@link GapImg }
     * 
     */
    public GapImg createGapImg() {
        return new GapImg();
    }

    /**
     * Create an instance of {@link Blockquote }
     * 
     */
    public Blockquote createBlockquote() {
        return new Blockquote();
    }

    /**
     * Create an instance of {@link MatchInteraction }
     * 
     */
    public MatchInteraction createMatchInteraction() {
        return new MatchInteraction();
    }

    /**
     * Create an instance of {@link SimpleMatchSet }
     * 
     */
    public SimpleMatchSet createSimpleMatchSet() {
        return new SimpleMatchSet();
    }

    /**
     * Create an instance of {@link SimpleAssociableChoice }
     * 
     */
    public SimpleAssociableChoice createSimpleAssociableChoice() {
        return new SimpleAssociableChoice();
    }

    /**
     * Create an instance of {@link FeedbackBlock }
     * 
     */
    public FeedbackBlock createFeedbackBlock() {
        return new FeedbackBlock();
    }

    /**
     * Create an instance of {@link GraphicGapMatchInteraction }
     * 
     */
    public GraphicGapMatchInteraction createGraphicGapMatchInteraction() {
        return new GraphicGapMatchInteraction();
    }

    /**
     * Create an instance of {@link AssociableHotspot }
     * 
     */
    public AssociableHotspot createAssociableHotspot() {
        return new AssociableHotspot();
    }

    /**
     * Create an instance of {@link HotspotInteraction }
     * 
     */
    public HotspotInteraction createHotspotInteraction() {
        return new HotspotInteraction();
    }

    /**
     * Create an instance of {@link HotspotChoice }
     * 
     */
    public HotspotChoice createHotspotChoice() {
        return new HotspotChoice();
    }

    /**
     * Create an instance of {@link GraphicOrderInteraction }
     * 
     */
    public GraphicOrderInteraction createGraphicOrderInteraction() {
        return new GraphicOrderInteraction();
    }

    /**
     * Create an instance of {@link SelectPointInteraction }
     * 
     */
    public SelectPointInteraction createSelectPointInteraction() {
        return new SelectPointInteraction();
    }

    /**
     * Create an instance of {@link GraphicAssociateInteraction }
     * 
     */
    public GraphicAssociateInteraction createGraphicAssociateInteraction() {
        return new GraphicAssociateInteraction();
    }

    /**
     * Create an instance of {@link SliderInteraction }
     * 
     */
    public SliderInteraction createSliderInteraction() {
        return new SliderInteraction();
    }

    /**
     * Create an instance of {@link ChoiceInteraction }
     * 
     */
    public ChoiceInteraction createChoiceInteraction() {
        return new ChoiceInteraction();
    }

    /**
     * Create an instance of {@link SimpleChoice }
     * 
     */
    public SimpleChoice createSimpleChoice() {
        return new SimpleChoice();
    }

    /**
     * Create an instance of {@link TemplateBlock }
     * 
     */
    public TemplateBlock createTemplateBlock() {
        return new TemplateBlock();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Caption }
     * 
     */
    public Caption createCaption() {
        return new Caption();
    }

    /**
     * Create an instance of {@link Col }
     * 
     */
    public Col createCol() {
        return new Col();
    }

    /**
     * Create an instance of {@link Colgroup }
     * 
     */
    public Colgroup createColgroup() {
        return new Colgroup();
    }

    /**
     * Create an instance of {@link Thead }
     * 
     */
    public Thead createThead() {
        return new Thead();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     */
    public Tr createTr() {
        return new Tr();
    }

    /**
     * Create an instance of {@link Td }
     * 
     */
    public Td createTd() {
        return new Td();
    }

    /**
     * Create an instance of {@link Div }
     * 
     */
    public Div createDiv() {
        return new Div();
    }

    /**
     * Create an instance of {@link MediaInteraction }
     * 
     */
    public MediaInteraction createMediaInteraction() {
        return new MediaInteraction();
    }

    /**
     * Create an instance of {@link HottextInteraction }
     * 
     */
    public HottextInteraction createHottextInteraction() {
        return new HottextInteraction();
    }

    /**
     * Create an instance of {@link OrderInteraction }
     * 
     */
    public OrderInteraction createOrderInteraction() {
        return new OrderInteraction();
    }

    /**
     * Create an instance of {@link ExtendedTextInteraction }
     * 
     */
    public ExtendedTextInteraction createExtendedTextInteraction() {
        return new ExtendedTextInteraction();
    }

    /**
     * Create an instance of {@link UploadInteraction }
     * 
     */
    public UploadInteraction createUploadInteraction() {
        return new UploadInteraction();
    }

    /**
     * Create an instance of {@link AssociateInteraction }
     * 
     */
    public AssociateInteraction createAssociateInteraction() {
        return new AssociateInteraction();
    }

    /**
     * Create an instance of {@link Th }
     * 
     */
    public Th createTh() {
        return new Th();
    }

    /**
     * Create an instance of {@link Tfoot }
     * 
     */
    public Tfoot createTfoot() {
        return new Tfoot();
    }

    /**
     * Create an instance of {@link Tbody }
     * 
     */
    public Tbody createTbody() {
        return new Tbody();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link And }
     * 
     */
    public And createAnd() {
        return new And();
    }

    /**
     * Create an instance of {@link Gt }
     * 
     */
    public Gt createGt() {
        return new Gt();
    }

    /**
     * Create an instance of {@link Ordered }
     * 
     */
    public Ordered createOrdered() {
        return new Ordered();
    }

    /**
     * Create an instance of {@link Divide }
     * 
     */
    public Divide createDivide() {
        return new Divide();
    }

    /**
     * Create an instance of {@link CustomOperator }
     * 
     */
    public CustomOperator createCustomOperator() {
        return new CustomOperator();
    }

    /**
     * Create an instance of {@link Random }
     * 
     */
    public Random createRandom() {
        return new Random();
    }

    /**
     * Create an instance of {@link Delete }
     * 
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link NumberIncorrect }
     * 
     */
    public NumberIncorrect createNumberIncorrect() {
        return new NumberIncorrect();
    }

    /**
     * Create an instance of {@link Substring }
     * 
     */
    public Substring createSubstring() {
        return new Substring();
    }

    /**
     * Create an instance of {@link Not }
     * 
     */
    public Not createNot() {
        return new Not();
    }

    /**
     * Create an instance of {@link FieldValue }
     * 
     */
    public FieldValue createFieldValue() {
        return new FieldValue();
    }

    /**
     * Create an instance of {@link Truncate }
     * 
     */
    public Truncate createTruncate() {
        return new Truncate();
    }

    /**
     * Create an instance of {@link Sum }
     * 
     */
    public Sum createSum() {
        return new Sum();
    }

    /**
     * Create an instance of {@link EqualRounded }
     * 
     */
    public EqualRounded createEqualRounded() {
        return new EqualRounded();
    }

    /**
     * Create an instance of {@link Multiple }
     * 
     */
    public Multiple createMultiple() {
        return new Multiple();
    }

    /**
     * Create an instance of {@link IntegerToFloat }
     * 
     */
    public IntegerToFloat createIntegerToFloat() {
        return new IntegerToFloat();
    }

    /**
     * Create an instance of {@link Lte }
     * 
     */
    public Lte createLte() {
        return new Lte();
    }

    /**
     * Create an instance of {@link Null }
     * 
     */
    public Null createNull() {
        return new Null();
    }

    /**
     * Create an instance of {@link Index }
     * 
     */
    public Index createIndex() {
        return new Index();
    }

    /**
     * Create an instance of {@link Match }
     * 
     */
    public Match createMatch() {
        return new Match();
    }

    /**
     * Create an instance of {@link TestVariables }
     * 
     */
    public TestVariables createTestVariables() {
        return new TestVariables();
    }

    /**
     * Create an instance of {@link IntegerDivide }
     * 
     */
    public IntegerDivide createIntegerDivide() {
        return new IntegerDivide();
    }

    /**
     * Create an instance of {@link Gte }
     * 
     */
    public Gte createGte() {
        return new Gte();
    }

    /**
     * Create an instance of {@link DurationLT }
     * 
     */
    public DurationLT createDurationLT() {
        return new DurationLT();
    }

    /**
     * Create an instance of {@link Contains }
     * 
     */
    public Contains createContains() {
        return new Contains();
    }

    /**
     * Create an instance of {@link Member }
     * 
     */
    public Member createMember() {
        return new Member();
    }

    /**
     * Create an instance of {@link Lt }
     * 
     */
    public Lt createLt() {
        return new Lt();
    }

    /**
     * Create an instance of {@link Correct }
     * 
     */
    public Correct createCorrect() {
        return new Correct();
    }

    /**
     * Create an instance of {@link NumberSelected }
     * 
     */
    public NumberSelected createNumberSelected() {
        return new NumberSelected();
    }

    /**
     * Create an instance of {@link PatternMatch }
     * 
     */
    public PatternMatch createPatternMatch() {
        return new PatternMatch();
    }

    /**
     * Create an instance of {@link NumberCorrect }
     * 
     */
    public NumberCorrect createNumberCorrect() {
        return new NumberCorrect();
    }

    /**
     * Create an instance of {@link IsNull }
     * 
     */
    public IsNull createIsNull() {
        return new IsNull();
    }

    /**
     * Create an instance of {@link RandomInteger }
     * 
     */
    public RandomInteger createRandomInteger() {
        return new RandomInteger();
    }

    /**
     * Create an instance of {@link Or }
     * 
     */
    public Or createOr() {
        return new Or();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link NumberPresented }
     * 
     */
    public NumberPresented createNumberPresented() {
        return new NumberPresented();
    }

    /**
     * Create an instance of {@link Power }
     * 
     */
    public Power createPower() {
        return new Power();
    }

    /**
     * Create an instance of {@link MapResponsePoint }
     * 
     */
    public MapResponsePoint createMapResponsePoint() {
        return new MapResponsePoint();
    }

    /**
     * Create an instance of {@link MapResponse }
     * 
     */
    public MapResponse createMapResponse() {
        return new MapResponse();
    }

    /**
     * Create an instance of {@link RandomFloat }
     * 
     */
    public RandomFloat createRandomFloat() {
        return new RandomFloat();
    }

    /**
     * Create an instance of {@link StringMatch }
     * 
     */
    public StringMatch createStringMatch() {
        return new StringMatch();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

    /**
     * Create an instance of {@link IntegerModulus }
     * 
     */
    public IntegerModulus createIntegerModulus() {
        return new IntegerModulus();
    }

    /**
     * Create an instance of {@link Subtract }
     * 
     */
    public Subtract createSubtract() {
        return new Subtract();
    }

    /**
     * Create an instance of {@link DurationGTE }
     * 
     */
    public DurationGTE createDurationGTE() {
        return new DurationGTE();
    }

    /**
     * Create an instance of {@link OutcomeMaximum }
     * 
     */
    public OutcomeMaximum createOutcomeMaximum() {
        return new OutcomeMaximum();
    }

    /**
     * Create an instance of {@link AnyN }
     * 
     */
    public AnyN createAnyN() {
        return new AnyN();
    }

    /**
     * Create an instance of {@link Round }
     * 
     */
    public Round createRound() {
        return new Round();
    }

    /**
     * Create an instance of {@link OutcomeMinimum }
     * 
     */
    public OutcomeMinimum createOutcomeMinimum() {
        return new OutcomeMinimum();
    }

    /**
     * Create an instance of {@link Equal }
     * 
     */
    public Equal createEqual() {
        return new Equal();
    }

    /**
     * Create an instance of {@link NumberResponded }
     * 
     */
    public NumberResponded createNumberResponded() {
        return new NumberResponded();
    }

    /**
     * Create an instance of {@link BaseValue }
     * 
     */
    public BaseValue createBaseValue() {
        return new BaseValue();
    }

    /**
     * Create an instance of {@link Default }
     * 
     */
    public Default createDefault() {
        return new Default();
    }

    /**
     * Create an instance of {@link Inside }
     * 
     */
    public Inside createInside() {
        return new Inside();
    }

    /**
     * Create an instance of {@link ContainerSize }
     * 
     */
    public ContainerSize createContainerSize() {
        return new ContainerSize();
    }

    /**
     * Create an instance of {@link AreaMapEntry }
     * 
     */
    public AreaMapEntry createAreaMapEntry() {
        return new AreaMapEntry();
    }

    /**
     * Create an instance of {@link AreaMapping }
     * 
     */
    public AreaMapping createAreaMapping() {
        return new AreaMapping();
    }

    /**
     * Create an instance of {@link AssessmentItem }
     * 
     */
    public AssessmentItem createAssessmentItem() {
        return new AssessmentItem();
    }

    /**
     * Create an instance of {@link ResponseDeclaration }
     * 
     */
    public ResponseDeclaration createResponseDeclaration() {
        return new ResponseDeclaration();
    }

    /**
     * Create an instance of {@link DefaultValue }
     * 
     */
    public DefaultValue createDefaultValue() {
        return new DefaultValue();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link CorrectResponse }
     * 
     */
    public CorrectResponse createCorrectResponse() {
        return new CorrectResponse();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link MapEntry }
     * 
     */
    public MapEntry createMapEntry() {
        return new MapEntry();
    }

    /**
     * Create an instance of {@link OutcomeDeclaration }
     * 
     */
    public OutcomeDeclaration createOutcomeDeclaration() {
        return new OutcomeDeclaration();
    }

    /**
     * Create an instance of {@link InterpolationTable }
     * 
     */
    public InterpolationTable createInterpolationTable() {
        return new InterpolationTable();
    }

    /**
     * Create an instance of {@link InterpolationTableEntry }
     * 
     */
    public InterpolationTableEntry createInterpolationTableEntry() {
        return new InterpolationTableEntry();
    }

    /**
     * Create an instance of {@link MatchTable }
     * 
     */
    public MatchTable createMatchTable() {
        return new MatchTable();
    }

    /**
     * Create an instance of {@link MatchTableEntry }
     * 
     */
    public MatchTableEntry createMatchTableEntry() {
        return new MatchTableEntry();
    }

    /**
     * Create an instance of {@link TemplateDeclaration }
     * 
     */
    public TemplateDeclaration createTemplateDeclaration() {
        return new TemplateDeclaration();
    }

    /**
     * Create an instance of {@link TemplateProcessing }
     * 
     */
    public TemplateProcessing createTemplateProcessing() {
        return new TemplateProcessing();
    }

    /**
     * Create an instance of {@link SetTemplateValue }
     * 
     */
    public SetTemplateValue createSetTemplateValue() {
        return new SetTemplateValue();
    }

    /**
     * Create an instance of {@link ExitTemplate }
     * 
     */
    public ExitTemplate createExitTemplate() {
        return new ExitTemplate();
    }

    /**
     * Create an instance of {@link TemplateCondition }
     * 
     */
    public TemplateCondition createTemplateCondition() {
        return new TemplateCondition();
    }

    /**
     * Create an instance of {@link TemplateIf }
     * 
     */
    public TemplateIf createTemplateIf() {
        return new TemplateIf();
    }

    /**
     * Create an instance of {@link SetDefaultValue }
     * 
     */
    public SetDefaultValue createSetDefaultValue() {
        return new SetDefaultValue();
    }

    /**
     * Create an instance of {@link SetCorrectResponse }
     * 
     */
    public SetCorrectResponse createSetCorrectResponse() {
        return new SetCorrectResponse();
    }

    /**
     * Create an instance of {@link TemplateElseIf }
     * 
     */
    public TemplateElseIf createTemplateElseIf() {
        return new TemplateElseIf();
    }

    /**
     * Create an instance of {@link TemplateElse }
     * 
     */
    public TemplateElse createTemplateElse() {
        return new TemplateElse();
    }

    /**
     * Create an instance of {@link Stylesheet }
     * 
     */
    public Stylesheet createStylesheet() {
        return new Stylesheet();
    }

    /**
     * Create an instance of {@link ItemBody }
     * 
     */
    public ItemBody createItemBody() {
        return new ItemBody();
    }

    /**
     * Create an instance of {@link ResponseProcessing }
     * 
     */
    public ResponseProcessing createResponseProcessing() {
        return new ResponseProcessing();
    }

    /**
     * Create an instance of {@link ResponseCondition }
     * 
     */
    public ResponseCondition createResponseCondition() {
        return new ResponseCondition();
    }

    /**
     * Create an instance of {@link ResponseIf }
     * 
     */
    public ResponseIf createResponseIf() {
        return new ResponseIf();
    }

    /**
     * Create an instance of {@link ResponseProcessingFragment }
     * 
     */
    public ResponseProcessingFragment createResponseProcessingFragment() {
        return new ResponseProcessingFragment();
    }

    /**
     * Create an instance of {@link SetOutcomeValue }
     * 
     */
    public SetOutcomeValue createSetOutcomeValue() {
        return new SetOutcomeValue();
    }

    /**
     * Create an instance of {@link ExitResponse }
     * 
     */
    public ExitResponse createExitResponse() {
        return new ExitResponse();
    }

    /**
     * Create an instance of {@link LookupOutcomeValue }
     * 
     */
    public LookupOutcomeValue createLookupOutcomeValue() {
        return new LookupOutcomeValue();
    }

    /**
     * Create an instance of {@link ResponseElseIf }
     * 
     */
    public ResponseElseIf createResponseElseIf() {
        return new ResponseElseIf();
    }

    /**
     * Create an instance of {@link ResponseElse }
     * 
     */
    public ResponseElse createResponseElse() {
        return new ResponseElse();
    }

    /**
     * Create an instance of {@link ModalFeedback }
     * 
     */
    public ModalFeedback createModalFeedback() {
        return new ModalFeedback();
    }

    /**
     * Create an instance of {@link AssessmentItemRef }
     * 
     */
    public AssessmentItemRef createAssessmentItemRef() {
        return new AssessmentItemRef();
    }

    /**
     * Create an instance of {@link PreCondition }
     * 
     */
    public PreCondition createPreCondition() {
        return new PreCondition();
    }

    /**
     * Create an instance of {@link BranchRule }
     * 
     */
    public BranchRule createBranchRule() {
        return new BranchRule();
    }

    /**
     * Create an instance of {@link ItemSessionControl }
     * 
     */
    public ItemSessionControl createItemSessionControl() {
        return new ItemSessionControl();
    }

    /**
     * Create an instance of {@link TimeLimits }
     * 
     */
    public TimeLimits createTimeLimits() {
        return new TimeLimits();
    }

    /**
     * Create an instance of {@link VariableMapping }
     * 
     */
    public VariableMapping createVariableMapping() {
        return new VariableMapping();
    }

    /**
     * Create an instance of {@link Weight }
     * 
     */
    public Weight createWeight() {
        return new Weight();
    }

    /**
     * Create an instance of {@link TemplateDefault }
     * 
     */
    public TemplateDefault createTemplateDefault() {
        return new TemplateDefault();
    }

    /**
     * Create an instance of {@link AssessmentResult }
     * 
     */
    public AssessmentResult createAssessmentResult() {
        return new AssessmentResult();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link SessionIdentifier }
     * 
     */
    public SessionIdentifier createSessionIdentifier() {
        return new SessionIdentifier();
    }

    /**
     * Create an instance of {@link TestResult }
     * 
     */
    public TestResult createTestResult() {
        return new TestResult();
    }

    /**
     * Create an instance of {@link ResponseVariable }
     * 
     */
    public ResponseVariable createResponseVariable() {
        return new ResponseVariable();
    }

    /**
     * Create an instance of {@link CandidateResponse }
     * 
     */
    public CandidateResponse createCandidateResponse() {
        return new CandidateResponse();
    }

    /**
     * Create an instance of {@link TemplateVariable }
     * 
     */
    public TemplateVariable createTemplateVariable() {
        return new TemplateVariable();
    }

    /**
     * Create an instance of {@link OutcomeVariable }
     * 
     */
    public OutcomeVariable createOutcomeVariable() {
        return new OutcomeVariable();
    }

    /**
     * Create an instance of {@link ItemResult }
     * 
     */
    public ItemResult createItemResult() {
        return new ItemResult();
    }

    /**
     * Create an instance of {@link AssessmentSection }
     * 
     */
    public AssessmentSection createAssessmentSection() {
        return new AssessmentSection();
    }

    /**
     * Create an instance of {@link Selection }
     * 
     */
    public Selection createSelection() {
        return new Selection();
    }

    /**
     * Create an instance of {@link Ordering }
     * 
     */
    public Ordering createOrdering() {
        return new Ordering();
    }

    /**
     * Create an instance of {@link AssessmentTest }
     * 
     */
    public AssessmentTest createAssessmentTest() {
        return new AssessmentTest();
    }

    /**
     * Create an instance of {@link TestPart }
     * 
     */
    public TestPart createTestPart() {
        return new TestPart();
    }

    /**
     * Create an instance of {@link TestFeedback }
     * 
     */
    public TestFeedback createTestFeedback() {
        return new TestFeedback();
    }

    /**
     * Create an instance of {@link OutcomeProcessing }
     * 
     */
    public OutcomeProcessing createOutcomeProcessing() {
        return new OutcomeProcessing();
    }

    /**
     * Create an instance of {@link OutcomeProcessingFragment }
     * 
     */
    public OutcomeProcessingFragment createOutcomeProcessingFragment() {
        return new OutcomeProcessingFragment();
    }

    /**
     * Create an instance of {@link ExitTest }
     * 
     */
    public ExitTest createExitTest() {
        return new ExitTest();
    }

    /**
     * Create an instance of {@link OutcomeCondition }
     * 
     */
    public OutcomeCondition createOutcomeCondition() {
        return new OutcomeCondition();
    }

    /**
     * Create an instance of {@link OutcomeIf }
     * 
     */
    public OutcomeIf createOutcomeIf() {
        return new OutcomeIf();
    }

    /**
     * Create an instance of {@link OutcomeElseIf }
     * 
     */
    public OutcomeElseIf createOutcomeElseIf() {
        return new OutcomeElseIf();
    }

    /**
     * Create an instance of {@link OutcomeElse }
     * 
     */
    public OutcomeElse createOutcomeElse() {
        return new OutcomeElse();
    }

    /**
     * Create an instance of {@link BankProfile }
     * 
     */
    public BankProfile createBankProfile() {
        return new BankProfile();
    }

    /**
     * Create an instance of {@link MetadataProfile }
     * 
     */
    public MetadataProfile createMetadataProfile() {
        return new MetadataProfile();
    }

    /**
     * Create an instance of {@link CategorizedStatistic }
     * 
     */
    public CategorizedStatistic createCategorizedStatistic() {
        return new CategorizedStatistic();
    }

    /**
     * Create an instance of {@link TargetObject }
     * 
     */
    public TargetObject createTargetObject() {
        return new TargetObject();
    }

    /**
     * Create an instance of {@link ContentProfile }
     * 
     */
    public ContentProfile createContentProfile() {
        return new ContentProfile();
    }

    /**
     * Create an instance of {@link OrdinaryStatistic }
     * 
     */
    public OrdinaryStatistic createOrdinaryStatistic() {
        return new OrdinaryStatistic();
    }

    /**
     * Create an instance of {@link QtiMetadata }
     * 
     */
    public QtiMetadata createQtiMetadata() {
        return new QtiMetadata();
    }

    /**
     * Create an instance of {@link UsageData }
     * 
     */
    public UsageData createUsageData() {
        return new UsageData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "adaptive")
    public JAXBElement<Boolean> createAdaptive(Boolean value) {
        return new JAXBElement<Boolean>(_Adaptive_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "usageDataVocabulary")
    public JAXBElement<String> createUsageDataVocabulary(String value) {
        return new JAXBElement<String>(_UsageDataVocabulary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "imsmd")
    public JAXBElement<Boolean> createImsmd(Boolean value) {
        return new JAXBElement<Boolean>(_Imsmd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "lomMetadata")
    public JAXBElement<Boolean> createLomMetadata(Boolean value) {
        return new JAXBElement<Boolean>(_LomMetadata_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "imsqtimd")
    public JAXBElement<Boolean> createImsqtimd(Boolean value) {
        return new JAXBElement<Boolean>(_Imsqtimd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "composite")
    public JAXBElement<Boolean> createComposite(Boolean value) {
        return new JAXBElement<Boolean>(_Composite_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "timeDependent")
    public JAXBElement<Boolean> createTimeDependent(Boolean value) {
        return new JAXBElement<Boolean>(_TimeDependent_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "templates")
    public JAXBElement<Boolean> createTemplates(Boolean value) {
        return new JAXBElement<Boolean>(_Templates_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "textElements")
    public JAXBElement<Boolean> createTextElements(Boolean value) {
        return new JAXBElement<Boolean>(_TextElements_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "listElements")
    public JAXBElement<Boolean> createListElements(Boolean value) {
        return new JAXBElement<Boolean>(_ListElements_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "objectElements")
    public JAXBElement<Boolean> createObjectElements(Boolean value) {
        return new JAXBElement<Boolean>(_ObjectElements_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "objectType")
    public JAXBElement<String> createObjectType(String value) {
        return new JAXBElement<String>(_ObjectType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "presentationElements")
    public JAXBElement<Boolean> createPresentationElements(Boolean value) {
        return new JAXBElement<Boolean>(_PresentationElements_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "tableElements")
    public JAXBElement<Boolean> createTableElements(Boolean value) {
        return new JAXBElement<Boolean>(_TableElements_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "imageElement")
    public JAXBElement<Boolean> createImageElement(Boolean value) {
        return new JAXBElement<Boolean>(_ImageElement_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "imageType")
    public JAXBElement<String> createImageType(String value) {
        return new JAXBElement<String>(_ImageType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "hypertextElement")
    public JAXBElement<Boolean> createHypertextElement(Boolean value) {
        return new JAXBElement<Boolean>(_HypertextElement_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "mathElement")
    public JAXBElement<Boolean> createMathElement(Boolean value) {
        return new JAXBElement<Boolean>(_MathElement_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "mathVariable")
    public JAXBElement<Boolean> createMathVariable(Boolean value) {
        return new JAXBElement<Boolean>(_MathVariable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "feedbackIntegrated")
    public JAXBElement<Boolean> createFeedbackIntegrated(Boolean value) {
        return new JAXBElement<Boolean>(_FeedbackIntegrated_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "feedbackModal")
    public JAXBElement<Boolean> createFeedbackModal(Boolean value) {
        return new JAXBElement<Boolean>(_FeedbackModal_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "rubric")
    public JAXBElement<Boolean> createRubric(Boolean value) {
        return new JAXBElement<Boolean>(_Rubric_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "printedVariables")
    public JAXBElement<Boolean> createPrintedVariables(Boolean value) {
        return new JAXBElement<Boolean>(_PrintedVariables_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InteractionTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "interactionType")
    public JAXBElement<InteractionTypeType> createInteractionType(InteractionTypeType value) {
        return new JAXBElement<InteractionTypeType>(_InteractionType_QNAME, InteractionTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "responseRules")
    public JAXBElement<Boolean> createResponseRules(Boolean value) {
        return new JAXBElement<Boolean>(_ResponseRules_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "rpTemplate")
    public JAXBElement<String> createRpTemplate(String value) {
        return new JAXBElement<String>(_RpTemplate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "rounding")
    public JAXBElement<Boolean> createRounding(Boolean value) {
        return new JAXBElement<Boolean>(_Rounding_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "regexp")
    public JAXBElement<Boolean> createRegexp(Boolean value) {
        return new JAXBElement<Boolean>(_Regexp_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeedbackTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "feedbackType")
    public JAXBElement<FeedbackTypeType> createFeedbackType(FeedbackTypeType value) {
        return new JAXBElement<FeedbackTypeType>(_FeedbackType_QNAME, FeedbackTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "itemTemplate")
    public JAXBElement<Boolean> createItemTemplate(Boolean value) {
        return new JAXBElement<Boolean>(_ItemTemplate_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "solutionAvailable")
    public JAXBElement<Boolean> createSolutionAvailable(Boolean value) {
        return new JAXBElement<Boolean>(_SolutionAvailable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "toolName")
    public JAXBElement<String> createToolName(String value) {
        return new JAXBElement<String>(_ToolName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "toolVersion")
    public JAXBElement<String> createToolVersion(String value) {
        return new JAXBElement<String>(_ToolVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsqti_v2p1", name = "toolVendor")
    public JAXBElement<String> createToolVendor(String value) {
        return new JAXBElement<String>(_ToolVendor_QNAME, String.class, null, value);
    }

}
