//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for qtiMetadata.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="qtiMetadata.Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}qtiMetadata.ContentGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "qtiMetadata.Type", propOrder = {
    "itemTemplate",
    "timeDependent",
    "composite",
    "interactionTypes",
    "feedbackType",
    "solutionAvailable",
    "toolName",
    "toolVersion",
    "toolVendor"
})
@XmlRootElement(name = "qtiMetadata")
public class QtiMetadata {

    protected Boolean itemTemplate;
    protected Boolean timeDependent;
    protected Boolean composite;
    @XmlElement(name = "interactionType")
    @XmlSchemaType(name = "NMTOKEN")
    protected List<InteractionTypeType> interactionTypes;
    @XmlSchemaType(name = "NMTOKEN")
    protected FeedbackTypeType feedbackType;
    protected Boolean solutionAvailable;
    protected String toolName;
    protected String toolVersion;
    protected String toolVendor;

    /**
     * Gets the value of the itemTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isItemTemplate() {
        return itemTemplate;
    }

    /**
     * Sets the value of the itemTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setItemTemplate(Boolean value) {
        this.itemTemplate = value;
    }

    /**
     * Gets the value of the timeDependent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTimeDependent() {
        return timeDependent;
    }

    /**
     * Sets the value of the timeDependent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTimeDependent(Boolean value) {
        this.timeDependent = value;
    }

    /**
     * Gets the value of the composite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isComposite() {
        return composite;
    }

    /**
     * Sets the value of the composite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setComposite(Boolean value) {
        this.composite = value;
    }

    /**
     * Gets the value of the interactionTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interactionTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInteractionTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InteractionTypeType }
     * 
     * 
     */
    public List<InteractionTypeType> getInteractionTypes() {
        if (interactionTypes == null) {
            interactionTypes = new ArrayList<InteractionTypeType>();
        }
        return this.interactionTypes;
    }

    /**
     * Gets the value of the feedbackType property.
     * 
     * @return
     *     possible object is
     *     {@link FeedbackTypeType }
     *     
     */
    public FeedbackTypeType getFeedbackType() {
        return feedbackType;
    }

    /**
     * Sets the value of the feedbackType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeedbackTypeType }
     *     
     */
    public void setFeedbackType(FeedbackTypeType value) {
        this.feedbackType = value;
    }

    /**
     * Gets the value of the solutionAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSolutionAvailable() {
        return solutionAvailable;
    }

    /**
     * Sets the value of the solutionAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSolutionAvailable(Boolean value) {
        this.solutionAvailable = value;
    }

    /**
     * Gets the value of the toolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolName() {
        return toolName;
    }

    /**
     * Sets the value of the toolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToolName(String value) {
        this.toolName = value;
    }

    /**
     * Gets the value of the toolVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolVersion() {
        return toolVersion;
    }

    /**
     * Sets the value of the toolVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToolVersion(String value) {
        this.toolVersion = value;
    }

    /**
     * Gets the value of the toolVendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolVendor() {
        return toolVendor;
    }

    /**
     * Sets the value of the toolVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToolVendor(String value) {
        this.toolVendor = value;
    }

}
