//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for responseCondition.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="responseCondition.Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}responseCondition.ContentGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responseCondition.Type", propOrder = {
    "responseIf",
    "responseElseIves",
    "responseElse"
})
@XmlRootElement(name = "responseCondition")
public class ResponseCondition {

    @XmlElement(required = true)
    protected ResponseIf responseIf;
    @XmlElement(name = "responseElseIf")
    protected List<ResponseElseIf> responseElseIves;
    protected ResponseElse responseElse;

    /**
     * Gets the value of the responseIf property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseIf }
     *     
     */
    public ResponseIf getResponseIf() {
        return responseIf;
    }

    /**
     * Sets the value of the responseIf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseIf }
     *     
     */
    public void setResponseIf(ResponseIf value) {
        this.responseIf = value;
    }

    /**
     * Gets the value of the responseElseIves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responseElseIves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponseElseIves().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResponseElseIf }
     * 
     * 
     */
    public List<ResponseElseIf> getResponseElseIves() {
        if (responseElseIves == null) {
            responseElseIves = new ArrayList<ResponseElseIf>();
        }
        return this.responseElseIves;
    }

    /**
     * Gets the value of the responseElse property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseElse }
     *     
     */
    public ResponseElse getResponseElse() {
        return responseElse;
    }

    /**
     * Sets the value of the responseElse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseElse }
     *     
     */
    public void setResponseElse(ResponseElse value) {
        this.responseElse = value;
    }

}
