//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3._2001.xinclude.Include;


/**
 * <p>Java class for responseElse.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="responseElse.Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}responseElse.ContentGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responseElse.Type", propOrder = {
    "includesAndResponseConditionsAndResponseProcessingFragments"
})
@XmlRootElement(name = "responseElse")
public class ResponseElse {

    @XmlElements({
        @XmlElement(name = "include", namespace = "http://www.w3.org/2001/XInclude", type = Include.class),
        @XmlElement(name = "responseCondition", type = ResponseCondition.class),
        @XmlElement(name = "responseProcessingFragment", type = ResponseProcessingFragment.class),
        @XmlElement(name = "setOutcomeValue", type = SetOutcomeValue.class),
        @XmlElement(name = "exitResponse", type = ExitResponse.class),
        @XmlElement(name = "lookupOutcomeValue", type = LookupOutcomeValue.class)
    })
    protected List<java.lang.Object> includesAndResponseConditionsAndResponseProcessingFragments;

    /**
     * Gets the value of the includesAndResponseConditionsAndResponseProcessingFragments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includesAndResponseConditionsAndResponseProcessingFragments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludesAndResponseConditionsAndResponseProcessingFragments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Include }
     * {@link ResponseCondition }
     * {@link ResponseProcessingFragment }
     * {@link SetOutcomeValue }
     * {@link ExitResponse }
     * {@link LookupOutcomeValue }
     * 
     * 
     */
    public List<java.lang.Object> getIncludesAndResponseConditionsAndResponseProcessingFragments() {
        if (includesAndResponseConditionsAndResponseProcessingFragments == null) {
            includesAndResponseConditionsAndResponseProcessingFragments = new ArrayList<java.lang.Object>();
        }
        return this.includesAndResponseConditionsAndResponseProcessingFragments;
    }

}
