//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for roundingMode.Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="roundingMode.Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="decimalPlaces"/&gt;
 *     &lt;enumeration value="significantFigures"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "roundingMode.Type")
@XmlEnum
public enum RoundingModeType {

    @XmlEnumValue("decimalPlaces")
    DECIMAL_PLACES("decimalPlaces"),
    @XmlEnumValue("significantFigures")
    SIGNIFICANT_FIGURES("significantFigures");
    private final String value;

    RoundingModeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoundingModeType fromValue(String v) {
        for (RoundingModeType c: RoundingModeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
