//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sessionStatus.Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sessionStatus.Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="final"/&gt;
 *     &lt;enumeration value="initial"/&gt;
 *     &lt;enumeration value="pendingResponseProcessing"/&gt;
 *     &lt;enumeration value="pendingSubmission"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "sessionStatus.Type")
@XmlEnum
public enum SessionStatusType {

    @XmlEnumValue("final")
    FINAL("final"),
    @XmlEnumValue("initial")
    INITIAL("initial"),
    @XmlEnumValue("pendingResponseProcessing")
    PENDING_RESPONSE_PROCESSING("pendingResponseProcessing"),
    @XmlEnumValue("pendingSubmission")
    PENDING_SUBMISSION("pendingSubmission");
    private final String value;

    SessionStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SessionStatusType fromValue(String v) {
        for (SessionStatusType c: SessionStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
