//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shape.Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="shape.Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="circle"/&gt;
 *     &lt;enumeration value="default"/&gt;
 *     &lt;enumeration value="ellipse"/&gt;
 *     &lt;enumeration value="poly"/&gt;
 *     &lt;enumeration value="rect"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "shape.Type")
@XmlEnum
public enum ShapeType {

    @XmlEnumValue("circle")
    CIRCLE("circle"),
    @XmlEnumValue("default")
    DEFAULT("default"),
    @XmlEnumValue("ellipse")
    ELLIPSE("ellipse"),
    @XmlEnumValue("poly")
    POLY("poly"),
    @XmlEnumValue("rect")
    RECT("rect");
    private final String value;

    ShapeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ShapeType fromValue(String v) {
        for (ShapeType c: ShapeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
