//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for templateProcessing.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="templateProcessing.Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}templateProcessing.ContentGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "templateProcessing.Type", propOrder = {
    "setTemplateValuesAndExitTemplatesAndTemplateConditions"
})
@XmlRootElement(name = "templateProcessing")
public class TemplateProcessing {

    @XmlElements({
        @XmlElement(name = "setTemplateValue", type = SetTemplateValue.class),
        @XmlElement(name = "exitTemplate", type = ExitTemplate.class),
        @XmlElement(name = "templateCondition", type = TemplateCondition.class),
        @XmlElement(name = "setDefaultValue", type = SetDefaultValue.class),
        @XmlElement(name = "setCorrectResponse", type = SetCorrectResponse.class)
    })
    protected List<java.lang.Object> setTemplateValuesAndExitTemplatesAndTemplateConditions;

    /**
     * Gets the value of the setTemplateValuesAndExitTemplatesAndTemplateConditions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the setTemplateValuesAndExitTemplatesAndTemplateConditions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSetTemplateValuesAndExitTemplatesAndTemplateConditions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetTemplateValue }
     * {@link ExitTemplate }
     * {@link TemplateCondition }
     * {@link SetDefaultValue }
     * {@link SetCorrectResponse }
     * 
     * 
     */
    public List<java.lang.Object> getSetTemplateValuesAndExitTemplatesAndTemplateConditions() {
        if (setTemplateValuesAndExitTemplatesAndTemplateConditions == null) {
            setTemplateValuesAndExitTemplatesAndTemplateConditions = new ArrayList<java.lang.Object>();
        }
        return this.setTemplateValuesAndExitTemplatesAndTemplateConditions;
    }

}
