//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testFeedbackAccess.Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="testFeedbackAccess.Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="atEnd"/&gt;
 *     &lt;enumeration value="during"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "testFeedbackAccess.Type")
@XmlEnum
public enum TestFeedbackAccessType {

    @XmlEnumValue("atEnd")
    AT_END("atEnd"),
    @XmlEnumValue("during")
    DURING("during");
    private final String value;

    TestFeedbackAccessType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TestFeedbackAccessType fromValue(String v) {
        for (TestFeedbackAccessType c: TestFeedbackAccessType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
