//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for usageData.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="usageData.Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}usageData.ContentGroup"/&gt;
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}usageData.AttrGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "usageData.Type", propOrder = {
    "ordinaryStatisticsAndCategorizedStatistics"
})
@XmlRootElement(name = "usageData")
public class UsageData {

    @XmlElements({
        @XmlElement(name = "ordinaryStatistic", type = OrdinaryStatistic.class),
        @XmlElement(name = "categorizedStatistic", type = CategorizedStatistic.class)
    })
    protected List<java.lang.Object> ordinaryStatisticsAndCategorizedStatistics;
    @XmlAttribute(name = "glossary")
    protected String glossary;

    /**
     * Gets the value of the ordinaryStatisticsAndCategorizedStatistics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ordinaryStatisticsAndCategorizedStatistics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrdinaryStatisticsAndCategorizedStatistics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrdinaryStatistic }
     * {@link CategorizedStatistic }
     * 
     * 
     */
    public List<java.lang.Object> getOrdinaryStatisticsAndCategorizedStatistics() {
        if (ordinaryStatisticsAndCategorizedStatistics == null) {
            ordinaryStatisticsAndCategorizedStatistics = new ArrayList<java.lang.Object>();
        }
        return this.ordinaryStatisticsAndCategorizedStatistics;
    }

    /**
     * Gets the value of the glossary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlossary() {
        return glossary;
    }

    /**
     * Sets the value of the glossary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlossary(String value) {
        this.glossary = value;
    }

}
