//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 03:51:03 AM CET 
//


package org.imsglobal.xsd.imsqti_v2p1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for view.Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="view.Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="author"/&gt;
 *     &lt;enumeration value="candidate"/&gt;
 *     &lt;enumeration value="proctor"/&gt;
 *     &lt;enumeration value="scorer"/&gt;
 *     &lt;enumeration value="testConstructor"/&gt;
 *     &lt;enumeration value="tutor"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "view.Type")
@XmlEnum
public enum ViewType {

    @XmlEnumValue("author")
    AUTHOR("author"),
    @XmlEnumValue("candidate")
    CANDIDATE("candidate"),
    @XmlEnumValue("proctor")
    PROCTOR("proctor"),
    @XmlEnumValue("scorer")
    SCORER("scorer"),
    @XmlEnumValue("testConstructor")
    TEST_CONSTRUCTOR("testConstructor"),
    @XmlEnumValue("tutor")
    TUTOR("tutor");
    private final String value;

    ViewType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ViewType fromValue(String v) {
        for (ViewType c: ViewType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
